name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: blog-frontend/package-lock.json
      
      - name: Install dependencies
        run: |
          cd blog-frontend
          npm ci --legacy-peer-deps
        env:
          CI: false
      
      - name: Build application
        run: |
          cd blog-frontend
          npm run build
        env:
          CI: false
          REACT_APP_API_URL: https://qalam-blogs-backend.vercel.app
          NODE_ENV: production
          DISABLE_ESLINT_PLUGIN: true
          GENERATE_SOURCEMAP: false
      
      - name: List build contents (Debug)
        run: |
          echo "Checking build directory contents:"
          ls -la blog-frontend/build/ || echo "Build directory not found"
          echo "Checking for index.html:"
          ls -la blog-frontend/build/index.html || echo "index.html not found"
      
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_SALMON_PEBBLE_0CF2BBB1E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          ###### Repository/Build Configurations ######
          app_location: "blog-frontend" # App source code path
          api_location: "" # No API (using Vercel backend)
          output_location: "build" # Built app content directory
          skip_app_build: true # We already built the app in previous step
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_SALMON_PEBBLE_0CF2BBB1E }}
          action: "close"
